import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import PrimaryDraw from "@/components/navbars/primary-draw";
import SecondaryDraw from "@/components/navbars/secondary-draw";
import { Separator } from "@/components/ui/separator";
import RootProvider from "@/components/providers/root-provider";
import MobileNavbar from "@/components/mobile/mobile-navbar";
import Navbar from "@/components/navbars/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("flex justify-center", inter.className)}>
        <RootProvider>
          <div className="mx-auto flex h-full w-full max-w-none flex-col">
            <MobileNavbar />
            <div className="flex h-full w-full overflow-hidden">
              <PrimaryDraw />
              <Separator orientation="vertical" />
              <SecondaryDraw />
              <Separator orientation="vertical" />
              {children}
              <Navbar />
            </div>
          </div>
        </RootProvider>
      </body>
    </html>
  );
}
