# when the service's volumes are set to ./*:/usr/src/*/, docker will reflect the changes in local environment

services:
  redis:
    image: redis:7.4.0-alpine
    container_name: redis

  django:
    build: ./
    image: nevalearntocode/djangonextjschat:latest
    command: gunicorn backend.wsgi:application --port 8000 --bind 0.0.0.0
    container_name: django
    volumes:
      - ./:/usr/src/django/
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - database
      - redis
      - uvicorn

  uvicorn:
    build: ./
    command: uvicorn backend.asgi:application --host 0.0.0.0 --port 8002
    ports:
      - 8002:8002

  database:
    image: postgres:16.3-alpine
    container_name: database
    volumes:
      - dj_chat_postgres:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    command: -p 5432

volumes:
    dj_chat_postgres:
