# Generated by Django 5.1 on 2024-09-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, default='http://127.0.0.1:8000/media/category/default-category-icon.png', null=True),
        ),
    ]
