# Generated by Django 5.1 on 2024-09-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
