# Generated by Django 5.1 on 2024-09-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_server_category_remove_channel_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
