# Generated by Django 5.1 on 2024-09-16 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_server_banner_server_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
