# Generated by Django 5.1 on 2024-09-17 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_server_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='banned',
            field=models.ManyToManyField(blank=True, related_name='server_banned', to=settings.AUTH_USER_MODEL),
        ),
    ]
