# Generated by Django 5.1 on 2024-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.TextField(blank=True, default='http://127.0.0.1:8000/media/channel/channel-banner-2.jpg', null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.TextField(blank=True, default='http://127.0.0.1:8000/media/channel/default-channel-icon.png', null=True),
        ),
    ]
