# Generated by Django 5.1 on 2024-09-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_banner_alter_channel_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='icon',
        ),
    ]
