# Generated by Django 5.1 on 2024-09-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_remove_channel_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='owner',
        ),
    ]
